"""
Django settings for calender project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '8!12#5-lreq!3fb&!+9ji_ok(au0wznv#!bqe0#un=e7#ak=w2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# REST Framework
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_PERMISSION_CLASSES': [],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json'
}

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'fcm_django',
    'push_notifications'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'calender.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'calender.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'calender',
        'USER': 'dev',
        'PASSWORD': 'admin',
        'HOST': '127.0.0.1',
        'PORT':'5432'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, '..','uploaded_media')
MEDIA_URL = '/media/'


EMAIL_USE_TLS = True 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_PASSWORD = 'umbrella9*7'
EMAIL_HOST_USER = 'umbrubayet@gmail.com'
EMAIL_PORT =587 
EMAIL_USE_SSL = False
SERVER_EMAIL = 'umbrubayet@gmail.com'



FCM_APIKEY = "AAAAlkj3tIM:APA91bELaQHJRy709Qlol7bAvbDfdioSQXQ64WEvj5xPgyj0ASiQOV-5H0JLgXXAeptQ9TAZfOlCAkjcq7qEDHFCHwYGTWUwicAPFVscP_Wliuer42t6BjsT9rPSFjshmQfmcNYFK8KI"


PUSH_NOTIFICATIONS_SETTINGS = {
"FCM_API_KEY": "AAAAlkj3tIM:APA91bF11FDRvlglrCYz_stuJBlX1h354eZ1FxZIYuJi_zz0zC2gJTTlFDQjPG_GfpeH236Nwn3D6jDBju97ZyVtVJlMjqXGO0tvfkApf-Vs-vUj9MYIXFhgy1vcAra68CCiUH1an-kQ",
}

FCM_DJANGO_SETTINGS = {
    "FCM_SERVER_KEY":"AAAAlkj3tIM:APA91bELaQHJRy709Qlol7bAvbDfdioSQXQ64WEvj5xPgyj0ASiQOV-5H0JLgXXAeptQ9TAZfOlCAkjcq7qEDHFCHwYGTWUwicAPFVscP_Wliuer42t6BjsT9rPSFjshmQfmcNYFK8KI"
}
